apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.deploymentName }}
spec:
  replicas: {{ $.Values.appTierReplicas }}
  selector:
    matchLabels:
      app: main
  revisionHistoryLimit: 0
  progressDeadlineSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main
        image: gulectufan/hwc-deployment:allishere
        ports:
        - containerPort: 11130
